services:
  database:
    build: ./database
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  
  api:
    build: ./api
    links:
      - "database:db"
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy