services:
  database:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
  
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "5000:5000"